
language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

branches:
  - master
  - develop

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - ng build:libs
  - ng build
  - ng lint
  - ng test